### Register user raw
POST http://localhost:5003/api/auth/register
Content-Type: application/json

{
    "email":"testing123@gmail.com",
    "pwd":"123"
}

###Login user raw
POST http://localhost:5006/api/auth/login
Content-Type: application/json

{
    "email":"diego@gmail.com",
    "pwd":"123"    
}

### Get all products
GET http://localhost:5003/api/products

### Create Product form-data
POST http://localhost:5006/api/product
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.MQ.h8xdF-oMjh4XqCjG06OLIHeKLZts8xQob_scZDPXxpE
Content-Type: application/json

{
    "name":"Iphone 130 Max",
    "price":12020,
    "stock":20,
    "brand":"Apple"
 
}
